### ISSUE TITLE
Add hasTextColor matcher

### ISSUE THREAD

**Issue by GergertRoman** [open-tool/ultron#21]
Missing matcher to check text color

**Comment by alex-tiurin** [comment]
It will be added little bit later. Probably in september after compose release.

For now you can create hasTextColor by your own as extension for Ultron framework.
You need to add a matcher(1) and describe an assertion(2).
 See an example of drawable assertions
1.  https://github.com/open-tool/ultron/blob/master/ultron/src/main/java/com/atiurin/ultron/custom/espresso/matcher/ResourceDrawableMatcher.kt
2.  https://github.com/open-tool/ultron/blob/master/ultron/src/main/java/com/atiurin/ultron/custom/espresso/assertion/DrawableAssertion.kt

**Comment by alex-tiurin** [comment]
Done.
Release - https://github.com/open-tool/ultron/releases/tag/2.0.4
