### ISSUE TITLE
Add interceptors

### ISSUE THREAD

**Issue by MaxFix** [open-tool/ultron#30]
Maybe cool to add interceptors for check request/response after actions?

**Comment by alex-tiurin** [comment]
Hi @MaxFix

We already have such mechanism. It is called **listeners**. Please, take a look at the doc - https://github.com/open-tool/ultron/wiki/Listeners

You also can check result handler feature of Ultron - https://github.com/open-tool/ultron/wiki/Handle-a-detailed-result-of-any-operation
