### ISSUE TITLE
Idling resources to ignore the endless async task for espresso

### ISSUE THREAD

**Issue by nikolai-ivanov** [open-tool/ultron#40]
Hi there, 

It's not an issue, it's a question if you already have the way in the framework how to ignore the endless async tasks.
I've not found a community where to ask it.

Is there a way how to say espresso to not wait for the specific endless async task from the AsyncTask.THREAD_POOL_EXECUTOR ?

Thanks for the advice.

**Comment by itsergpot** [comment]
Hello there,

Long story short - nope, as i know. There is no way to say espresso to do sth forcibly. But you can avoid espresso mechanism of waiting idle if you don`t use viewintercation class. It means that you need get view from matcher forcibly and try to check/assert that by your wrapper under the view.

I`m preparing some special stuff to extract the view (https://github.com/open-tool/ultron/pull/39) and you can write you own assertion under the view... for example isDisplayed() it is simple check:

fun View.isViewVisibleOnScreen() = this.getGlobalVisibleRect(Rect())
        && withEffectiveVisibility(ViewMatchers.Visibility.VISIBLE).matches(this)
        
and then you can make some extension for ultron to make special wrapper for step fail cases, when the result doesnt respond to your expectations and tests needs some extra tries to reach expected result. (check executeAction/executeAssertion mechanism)

Keep us tuned if it suitable for you.

**Comment by itsergpot** [comment]
You can also join the Telegram group https://t.me/ultron_framework for future conversations and questions.
