### ISSUE TITLE
Custom name for matcher object for Espresso, UiAutomator, Compose

### ISSUE THREAD

**Issue by alex-tiurin** [open-tool/ultron#49]
Use in exception message

**Comment by NighthawkHK** [comment]
Is that mean there will be an option to setup custom message for assertion?

**Comment by alex-tiurin** [comment]
Custom message will be supported additionally.
This one is about the UI  element information. Released - [2.3.1](https://github.com/open-tool/ultron/releases/tag/2.3.1)
