### ISSUE TITLE
Нow can I specify the order in which tests are run?

### ISSUE THREAD

**Issue by SuleymanovTat** [open-tool/ultron#64]
How can I specify the order in which tests are run? 

Example LoginTest.kt, Example1Test.kt, Example2Test.kt, ExitTest.kt

Thank you in advance)

**Comment by alex-tiurin** [comment]
Hi,

Generally, tests execution order  dependency is a bad practice. I recommend to change test data  prepareation approach. Each test should be independent even in a scope of single class.
Ultron provides the ability to prepare data for single test. You can read about it [here ](https://github.com/open-tool/ultron/wiki/Test-conditions-management)

Below advices are a BAD practice.  

 The framework doesn't provide an ability to manipulate tests order. This task is JUnit4 Runner responsibility. It identifies the order by using reflection and particulary the name of test function.
 In scope of single class you can give the proper name to provide the order, like `test1`, `test2`.
 
 I'm not sure but probably you can set the order of classes execution by creating a TestSuite
 
 ```
 import org.junit.runners.Suite;
import org.junit.runner.RunWith;

@RunWith(Suite.class)
@Suite.SuiteClasses({TestClass1.class, TestClass2.class})
public class TestSuite {
  //nothing
}
```
