### ISSUE TITLE
setup UltronComposeConfig for default unmerged tree = true

### ISSUE THREAD

**Issue by itsergpot** [open-tool/ultron#66]
need setup cfg for default unmerged tree option = true

**Comment by alex-tiurin** [comment]
PR - https://github.com/open-tool/ultron/pull/75

Released [2.5.0-alpha09]( https://github.com/open-tool/ultron/releases/tag/2.5.0-alpha09)

```kotlin
UltronComposeConfig.apply {
     useUnmergedTree = true
}
```
